newcastlex_mtn101x_1t2017_auth_user_prod {
  dataValues:
   { primKey: 1,
     id: '9954466',
     username: 'christinemceachern2',
     first_name: null,
     last_name: null,
     email: 'cmceachern@edx.org',
     password: null,
     is_staff: 1,
     is_active: 1,
     is_superuser: 0,
     last_login: '2017-10-06 18:15:17.122825',
     date_joined: '2016-03-07 18:08:24',
     status: null,
     email_key: null,
     avatar_type: null,
     country: null,
     show_country: 0,
     date_of_birth: null,
     interesting_tags: null,
     ignored_tags: null,
     email_tag_filter_strategy: 0,
     display_tag_filter_strategy: 0,
     consecutive_days_visit_count: 0 },
  _previousDataValues:
   { primKey: 1,
     id: '9954466',
     username: 'christinemceachern2',
     first_name: null,
     last_name: null,
     email: 'cmceachern@edx.org',
     password: null,
     is_staff: 1,
     is_active: 1,
     is_superuser: 0,
     last_login: '2017-10-06 18:15:17.122825',
     date_joined: '2016-03-07 18:08:24',
     status: null,
     email_key: null,
     avatar_type: null,
     country: null,
     show_country: 0,
     date_of_birth: null,
     interesting_tags: null,
     ignored_tags: null,
     email_tag_filter_strategy: 0,
     display_tag_filter_strategy: 0,
     consecutive_days_visit_count: 0 },
  _changed: {},
  _modelOptions:
   { timestamps: false,
     validate: {},
     freezeTableName: true,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     hooks: {},
     indexes: [],
     name:
      { plural: 'newcastlex_mtn101x_1t2017_auth_user_prods',
        singular: 'newcastlex_mtn101x_1t2017_auth_user_prod' },
     omitNull: false,
     tableName: 'newcastlex_mtn101x_1t2017_auth_user_prod',
     sequelize:
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [Object],
        queryInterface: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: {},
        test: [Object] },
     uniqueKeys: {} },
  _options:
   { isNewRecord: false,
     _schema: null,
     _schemaDelimiter: '',
     raw: true,
     attributes:
      [ 'primKey',
        'id',
        'username',
        'first_name',
        'last_name',
        'email',
        'password',
        'is_staff',
        'is_active',
        'is_superuser',
        'last_login',
        'date_joined',
        'status',
        'email_key',
        'avatar_type',
        'country',
        'show_country',
        'date_of_birth',
        'interesting_tags',
        'ignored_tags',
        'email_tag_filter_strategy',
        'display_tag_filter_strategy',
        'consecutive_days_visit_count' ] },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false }
